name: Pruebas y despliegue
on: [push]
jobs: 
run-on: ubuntu-latest
steps:
uses: /checkout@v2
run: | apt-get install-

name: Pruebas y despliegue
on:
  push:
    branches:
      - main
jobs:
  pruebas:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Instalar dependencias
        run: npm install
      - name: Ejecutar pruebas
        run: npm test

  despliegue:
    needs: pruebas
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Desplegar aplicación
        run: |
          cd repo
          npm ci
          npm run build
          npm start

