name: Pruebas y despliegue
on: [push]
jobs: 
run-on: ubuntu-latest
steps:
uses: /checkout@v2
run: | apt-get install-

      - name: Ejecutar Pruebas
        run: |
          npm install
          npm test

  pruebas:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Desplegar aplicación
        run: |
          cd repo
          npm ci
          npm run build
          npm start
