name: Pruebas y Despliegue

on:
  push:
    branches:
      - main

jobs:
  pruebas:
    runs-on: ubuntu-latest

    steps:
    - name: Verificar código
      uses: actions/checkout@v2

    - name: Configurar entorno
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git curl

    - name: Ejecutar pruebas
      run: |
        npm ci
        npm test

  despliegue:
    needs: pruebas
    runs-on: ubuntu-latest

    steps:
    - name: Desplegar aplicación
      run: |
        cd repo
        npm ci
        npm run build
        npm start
