name: Pruebas y despliegue
on: [push]
jobs: 
run-on: ubuntu-latest
steps:
uses: /checkout@v2
run: | apt-get install-

name: Ejecutar Pruebas
on:
push:
jobs:
pruebas:
run-on: ubuntu-latest
steps:
uses: /checkout@v2
name: Instalar dependencias
run: | npm test
despliegue:
needs: Pruebas
run-on: ubuntu-latest
steps:
uses: /checkout@v2
name: Desplegar aplicación
 run: |
    cd repo
    npm ci
    npm run build
    npm start
